packages:
  - apps/*
allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  esbuild: true
  msgpackr-extract: false
  prisma: true
  unrs-resolver: true

# Disable interactive prompt during prune (required for CI/Docker)
confirmModulesPurge: false
